# Compresses the config UI at build time and emits src/webui_gz.h.
#
# WEBUI_HTML was 57,858 B of plain HTML/CSS/JS sitting uncompressed in flash --
# 8% of the whole image, on a board whose OTA slot had 960 B of headroom left.
# gzip -9 takes it to 19,847 B, so this buys back ~38 KB. The page is served
# verbatim (one send_P, no placeholder substitution), which is what makes
# compressing it safe at all: there is nothing to patch into the bytes.
#
# GENERATED AT BUILD TIME, deliberately, rather than committing the byte array:
# a committed array silently goes stale the first time someone edits the HTML
# and forgets to regenerate, and the failure mode is a device serving a UI that
# does not match its own source. src/webui.h stays the single authoring source
# and is edited exactly as before.
#
# src/webui_gz.h is .gitignore'd on purpose. scripts/git_sha.py stamps a "+"
# (dirty) suffix when `git status --porcelain` reports ANYTHING, untracked
# included, and scripts/preflash_check.sh refuses a dirty image -- so a tracked
# or unignored generated file would make every build unflashable.
Import("env")
import gzip
import os
import re
import sys

SRC = os.path.join("src", "webui.h")
OUT = os.path.join("src", "webui_gz.h")


def _fail(msg):
    # Hard stop. A silent fallback here would produce a device serving an empty
    # or stale config page, which is far worse than a failed build.
    sys.stderr.write("webui_gz: %s\n" % msg)
    env.Exit(1)


def build():
    if not os.path.exists(SRC):
        _fail("%s not found" % SRC)
    src = open(SRC, encoding="utf-8").read()
    m = re.search(r'R"HTMLPAGE\((.*)\)HTMLPAGE";', src, re.S)
    if not m:
        _fail("could not find the R\"HTMLPAGE(...)\" raw string in %s" % SRC)
    html = m.group(1).encode("utf-8")
    if len(html) < 1000:
        _fail("extracted HTML is only %d B -- refusing, the regex is wrong"
              % len(html))

    # mtime=0 so the output is byte-identical for identical input: the build is
    # reproducible and the image md5 in preflash_check.sh means something.
    gz = gzip.compress(html, 9, mtime=0)

    body = []
    for i in range(0, len(gz), 16):
        body.append("  " + ",".join("0x%02X" % b for b in gz[i:i + 16]) + ",")
    text = (
        "// GENERATED by scripts/webui_gz.py at build time -- DO NOT EDIT, and do not\n"
        "// commit it. Edit src/webui.h; this file is rebuilt from it every build.\n"
        "// %d B of HTML -> %d B gzip.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        "static const uint8_t WEBUI_GZ[] PROGMEM = {\n%s\n};\n"
        "static const size_t WEBUI_GZ_LEN = %d;\n"
        % (len(html), len(gz), "\n".join(body), len(gz))
    )

    # Only rewrite when the content actually changes, so an unchanged UI does
    # not force a rebuild of WebPortal.cpp on every single build.
    if os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == text:
        return
    open(OUT, "w", encoding="utf-8").write(text)
    print("webui_gz: %d B HTML -> %d B gzip (saved %d B)"
          % (len(html), len(gz), len(html) - len(gz)))


build()
